input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ssh-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug } # Opcional: imprime los logs en la terminal para depurar
}
